sudo: required

language: go

jobs:
  include:
  - stage: test-user
    name: User service tests
    script: cd user && docker-compose up --build user && cd ..
  - stage: test-auth
    name: Auth service tests
    script: cd auth && docker-compose up --build auth && cd ..
  - stage: test-match
    name: Match service tests
    script: cd match && docker-compose up --build match && cd ..
  - stage: deploy
    if: branch = master
    script: sh push-image.sh

