sudo: required

language: go

jobs:
  include:
  - stage: test
    name: tests
    # Run unit and integration tests
    script: for svc in user auth match; do cd $svc && docker-compose up --build $svc && cd ..; done
  - stage: deploy
    if: branch = master
    script: sh push-image.sh

