version: '3'

services:
  user:
    build: ./user
    ports:
      - "80:80" 
    networks: 
      - user-network 

  user-db:
    image: postgres:12.1 
    environment:
      - PGUSER=postgres
    volumes:
      - ./user-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - user-network 

  matches:
    build: ./matches
    ports:
      - "81:80" 
    networks: 
      - matches-network 
    
  matches-db:
    image: postgres:12.1 
    environment:
      - PGUSER=postgres
    volumes:
      - ./matches-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - matches-network 
  

networks:
  user-network:
  matches-network:
