# Service to expose the auth-db to auth service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-db
  name: auth-db
spec:
  ports:
  - name: "db"
    port: 5432
    targetPort: 5432
  selector:
    app: auth
    kind: db
