{
 "title": "Auth Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Register Auth Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "rate(auth_request_success_total{request_type=\"register\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_request_failure_total{request_type=\"register\"}[5m])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "DB Register Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time (seconds)" }
   ],
   "targets": [
    {
     "expr": "auth_database_request_seconds{quantile=\"0.5\",query_type=\"register\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "auth_database_request_seconds{quantile=\"0.9\",query_type=\"register\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "auth_database_request_seconds{quantile=\"0.95\",query_type=\"register\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "auth_database_request_seconds{quantile=\"0.99\",query_type=\"register\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Login Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "rate(auth_request_success_total{request_type=\"login\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_request_failure_total{request_type=\"login\"}[5m])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "DB Login Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Time (seconds)" }
   ],
   "targets": [
    {
     "expr": "auth_database_request_seconds{quantile=\"0.5\",query_type=\"login\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "auth_database_request_seconds{quantile=\"0.9\",query_type=\"login\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "auth_database_request_seconds{quantile=\"0.95\",query_type=\"login\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "auth_database_request_seconds{quantile=\"0.99\",query_type=\"login\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  }
 ]
}