{
 "title": "Match Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "List Match Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "rate(match_request_success_total{request_type=\"list\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(match_request_failure_total{request_type=\"list\"}[5m])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "DB List Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time (seconds)" }
   ],
   "targets": [
    {
     "expr": "match_database_request_seconds{quantile=\"0.5\",query_type=\"list\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.9\",query_type=\"list\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.95\",query_type=\"list\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.99\",query_type=\"list\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Create Match Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "rate(match_request_success_total{request_type=\"create\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(match_request_failure_total{request_type=\"create\"}[5m])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "DB Create Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Time (seconds)" }
   ],
   "targets": [
    {
     "expr": "match_database_request_seconds{quantile=\"0.5\",query_type=\"create\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.9\",query_type=\"create\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.95\",query_type=\"create\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.99\",query_type=\"create\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Read Match Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "rate(match_request_success_total{request_type=\"read\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(match_request_failure_total{request_type=\"read\"}[5m])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "DB Read Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Time (seconds)" }
   ],
   "targets": [
    {
     "expr": "match_database_request_seconds{quantile=\"0.5\",query_type=\"read\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.9\",query_type=\"read\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.95\",query_type=\"read\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.99\",query_type=\"read\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Update Match Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "rate(match_request_success_total{request_type=\"update\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(match_request_failure_total{request_type=\"update\"}[5m])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "DB Update Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Time (seconds)" }
   ],
   "targets": [
    {
     "expr": "match_database_request_seconds{quantile=\"0.5\",query_type=\"update\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.9\",query_type=\"update\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.95\",query_type=\"update\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.99\",query_type=\"update\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Delete Match Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "rate(match_request_success_total{request_type=\"delete\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(match_request_failure_total{request_type=\"delete\"}[5m])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "DB Delete Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Time (seconds)" }
   ],
   "targets": [
    {
     "expr": "match_database_request_seconds{quantile=\"0.5\",query_type=\"delete\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.9\",query_type=\"delete\"}",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.95\",query_type=\"delete\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "match_database_request_seconds{quantile=\"0.99\",query_type=\"delete\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  }
 ]
}