# Persistent Volume that stored Postgres' data
kind: PersistentVolume
apiVersion: v1
metadata:
  name: user-db-volume
  labels:
    type: local
    app: user-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/data/user-db"
---
 # The claim into the persistent storage used by the pod to store
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: user-db
  name: user-db-claim
spec:
  accessModes:
  - ReadWriteMany
  volumeName: user-db-volume
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
