# Match service that exposes the go endpoint to the cluster
apiVersion: v1
kind: Service
metadata:
  labels:
    app: match
  name: match
spec:
  ports:
  - name: "api"
    port: 81
    targetPort: 81
  - name: "prom"
    port: 2113
    targetPort: 2113
  selector:
    app: match
    kind: service
