# Service to expose the match-db to matches service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: match-db
  name: match-db
spec:
  ports:
  - name: "db"
    port: 5432
    targetPort: 5432
  selector:
    app: match
    kind: db
