version: '3'

services:
  user:
    build: 
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - user-db
    networks: 
      - user-network 

  user-db:
    image: postgres:12.1 
    environment:
      - PGUSER=postgres
    volumes:
      - ./../user-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - user-network 

networks:
  user-network:
